name: Luo Lei's Blog
#url: luoleicn.github.io
baseurl: ""

# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

paginate:         1

# Custom vars
version:          1.0.0

github:
  repo:           github.com/luoleicn/luoleicn.github.io
safe: false
sitemapurl: "http://luoleicn.github.io"
