name: Luo Lei's Blog
#url: luoleicn.github.io
baseurl: ""

# Dependencies
#markdown:         redcarpet
#pygments:         true
#highlighter:         true
rouge:         true

# Permalinks
permalink:        pretty

paginate:         1

gems: [jekyll-paginate]

# Custom vars
version:          1.0.0

github:
  repo:           github.com/luoleicn/luoleicn.github.io
safe: false
#sitemapurl: "http://luoleicn.github.io"
sitemapurl: "http://www.luolei.info"

theme: jekyll-theme-cayman
gem "github-pages", group: :jekyll_plugins
